# Generated by Django 3.0.6 on 2020-05-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=60)),
                ('age', models.SmallIntegerField()),
                ('_gender', models.SmallIntegerField(db_column='gender')),
            ],
        ),
    ]
