# Generated by Django 3.0.6 on 2020-05-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0003_auto_20200509_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human',
            options={'ordering': ['-pk']},
        ),
    ]
